// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRLmBPJMYq6uK55h2G2CdtRPi30eN8cU',
    appId: '1:60039035240:web:b8101e66f06c6ee48e7edd',
    messagingSenderId: '60039035240',
    projectId: 'app-flutter-avaliacao-final',
    authDomain: 'app-flutter-avaliacao-final.firebaseapp.com',
    storageBucket: 'app-flutter-avaliacao-final.appspot.com',
    measurementId: 'G-842PNFGW0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRWYDyT5ro1zudoSZjAO_Bvw_bpTXxIE',
    appId: '1:60039035240:android:37088ad375b04f778e7edd',
    messagingSenderId: '60039035240',
    projectId: 'app-flutter-avaliacao-final',
    storageBucket: 'app-flutter-avaliacao-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFIEvD3ug50m9C_3Fwo0jGMa3ClazrGqo',
    appId: '1:60039035240:ios:f4ec9034368237418e7edd',
    messagingSenderId: '60039035240',
    projectId: 'app-flutter-avaliacao-final',
    storageBucket: 'app-flutter-avaliacao-final.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAvaliacaoFinal',
  );

}